---
- name: INSTALL ZABBIX-AGENT
  win_chocolatey: 
    name: zabbix-agent
    state: present
  become: yes
  become_user: svc.tfs
  become_method: runas

- name: FIREWALL ADD RULE TO ALLOW ZABBIX-AGENT ON TCP PORT 10050
  win_firewall_rule:
    name: SMTP
    localport: 10050
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: STOPPED SERVICE ZABBIX-AGENT
  win_shell:  Stop-Service -Name "Zabbix*"
  register: zabbix_stopped
- debug:
      var: zabbix_stopped.rc

- name: GET HOSTNAME
  win_shell: hostname
  register: meuhost
- debug:
      var: meuhost.stdout

- name: DEFINED MY HOST TO ZABBIX-SERVER
  set_fact:
    host_zabbix_agent: "{{ meuhost.stdout }}"

- debug:
      var: host_zabbix_agent     

- name: REGEX  AND CONFIG SERVER ACTICE 
  win_lineinfile:
    path: C:\ProgramData\zabbix\zabbix_agentd.conf
    regex: 'ServerActive=127.0.0.1'
    line: 'ServerActive=SEU IP'

- name: REGEX  AND CONFIG  SERVER
  win_lineinfile:
    path: C:\ProgramData\zabbix\zabbix_agentd.conf
    regex: 'Server=127.0.0.1'
    line: 'Server=SEU IP'    

- name: REGEX  AND CONFIG  HOSTNAME
  win_lineinfile:
    path: C:\ProgramData\zabbix\zabbix_agentd.conf
    regex: 'Hostname=Windows host'
    line: 'Hostname={{ host_zabbix_agent }}'    

- name: STARTED SERVICE ZABBIX-AGENT
  win_shell:  Start-Service -Name "Zabbix*"
  register: zabbix_started
- debug:
      var: zabbix_started.rc

- name: GET SERVICE ZABBIX-AGENT
  win_shell:  Get-Service -Name "Zabbix*"
  register: zabbix_get
- debug:
      var: zabbix_get.stdout_lines      